/**********************************************************************************
* @File      COnfig.h.in
* @Author    Alexis Nicole Benini, Ph.D.
* @Date      May 18th, 2022
* @Copyright RedWire Space
**********************************************************************************/

/** 
 *  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 *  !!! DO NOT EDIT THIS FILE !!!
 *  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 */

#pragma once

#ifndef _CONFIG_H
#define _CONFIG_H

#define VERSION_MAJOR 0
#define VERSION_MINOR 1

#define GIT_HASH ""

#ifndef _EXPORT
  #if (defined _WIN32 || defined WINCE || defined __CYGWIN__)
    #define _EXPORT __declspec(dllexport)
  #elif defined __GNUC__ && __GNUC__ >= 4
    #define _EXPORT __attribute__ ((visibility ("default")))
  #endif
#endif

/////////////////////////////////////////////////////
// Definition of packed structs for Linux and Windows
/////////////////////////////////////////////////////
#ifdef __GNUC__
#define PACK( __Declaration__ ) __Declaration__ __attribute__((__packed__))
#endif
// --------------------------------------------------
#ifdef _MSC_VER
#define PACK( __Declaration__ ) __pragma( pack(push, 1) ) __Declaration__ __pragma( pack(pop))
#endif
/////////////////////////////////////////////////////

/* #undef WITH_LOGGING */

#endif // ! _CONFIG_H
